[SDPTA-1019] User Site Permissions
dpc-sdp/tide_demo_content pull request #79
Opened 2024-02-19 04:18 UTC by klaukl

2024-02-19 22:47 UTC, klaukl commented
Hey @vincent-gao I don't need to worry about below right?
```
  Configuration objects provided by <em class="placeholder">tide_test</em> ha  
  ve unmet dependencies: <em class="placeholder">node.type.test (wysiwyg_temp  
  late)</em>                                                                   
                                             
```

I think it only occurs when testing / reference branch. The wysiwyg_template isn't in the master branch

2024-02-21 22:43 UTC, vincent-gao requested changes

2024-02-21 22:48 UTC, klaukl commented on tide_demo_content.install
> +function getAllSitesAndSiteSections() {
Fixed

2024-02-21 22:53 UTC, vincent-gao commented
hey @klaukl could you please also update` tide_test` by removing `wysiwyg_template` from `node.type.test` yaml file.

2024-02-21 22:54 UTC, vincent-gao approved these changes

2024-02-22 23:31 UTC, merged

2024-08-01 23:56 UTC, anthony-malkoun reviewed
This gels with what I was seeing in profiling that it was just doing too many SQL queries.